### ISSUE TITLE
Browscap-php result not corectly implemented

### ISSUE THREAD

**Issue by mimmi20** [ThaDafinser/UserAgentParser#3]
The used properties `win32` and `win64` are true only for Windows. If tyou want to detect also other platforms, use the `platform_bits` property.
The platform version can be detected with the `platform_version` property.
The device brand can be detected with the `device_brand_name` property.
The device model can be detected with the `device_name` property.

To detect the device properties you need the `full_php_browscap.ini` file.

**Comment by ThaDafinser** [comment]
Thank you for the feedback @mimmi20 ! I added the `device` and `platform` support in the latest commit: https://github.com/ThaDafinser/UserAgentParser/blob/master/src/Provider/BrowscapPhp.php#L207

I removed the bit detection for now ...because only Browscap and Piwik do that detection and in Piwik it's the Architecture (x86/ x64) which i dont know if its always (are there edge cases?) the same like bits?

**Comment by mimmi20** [comment]
In Browscap we detect the Bits only if they are mentioned in the useragent, and then also not on OSX. The reason for that is the compexity we would add. On ARM systems the bit count is not part of the useragent.

**Comment by ThaDafinser** [comment]
Thank you for the informations.

A last question for now: Are the *.php files here are deprecated? https://github.com/browscap/browscap/tree/master/src/Browscap

**Comment by mimmi20** [comment]
No.
The package browscap/browscap is there for creating the ini files.
The package browscap/browscap-php is there to use the ini files for detection.
